### ISSUE TITLE
Bower install failing

### ISSUE THREAD

**Issue by milleraundra** [safetychanger/iron-swiper#10]
I have `bower` installed and tried to run `bower install iron-swiper --save` in my project, but I got the following response.

[iron-swiper-bower-fail.txt](https://github.com/safetychanger/iron-swiper/files/714986/iron-swiper-bower-fail.txt)

Can you help?

**Comment by rubenstolk** [comment]
Uhm... I renamed the project today from `sc-swiper` to `iron-swiper` and forgot to publish it. Just did so, so it should work now!

Thanks @milleraundra!
