### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ToeFungi** [safetychanger/iron-swiper#19]
It doesn't seem like there currently exists a way to get the current slide's index. As you see on iron-select or one of those elements, you are presented with `selected=` and you can specify the index of the selected element. My use case requires me to be able to swipe between the pages and know what page I am on so I can prepare the next step

**Comment by dougchestnut** [comment]
The `selected` property should give you the index of the current slide, and notify on slide change (swipe).

**Comment by ToeFungi** [comment]
@dougchestnut Interesting... It doesn't seem to be a property. I'm using Chrome Dev tools with the swiper selected as $0 and it returns undefined

**Comment by dougchestnut** [comment]
Check out the `demo/selected.html` demo
I just did a fresh checkout and it seems to be working.  It shows the selected property being used to keep two swipers in sync and then also shows the index.

**Comment by rubenstolk** [comment]
@ToeFungi closing this issue until further notice...
