### ISSUE TITLE
Working with the latest Polymer and/or Polymer Starter Kit 1.1.1?

### ISSUE THREAD

**Issue by espeed** [safetychanger/iron-swiper#2]
Is this working with the latest Polymer?

Nothing is displaying -- tried several ways, including the latest version of the Polymer Starter Kit (v1.1.1)...

https://github.com/polymerelements/polymer-starter-kit/releases

**Comment by rubenstolk** [comment]
I'm running it in an app that was derived from PSK, it should just work. Please share your code sample so I can have a look.

**Comment by jegade** [comment]
I replaced initialize: with attach and it's working again. Try to create a pr soon.

**Comment by PChild** [comment]
@jegade Could you share your code? I'm also having issues with getting sc-swiper elements to display.

**Comment by jegade** [comment]
I created a PR for the fix #4
