### ISSUE TITLE
Ready for the next release?

### ISSUE THREAD

**Issue by JaySunSyn** [safetychanger/iron-swiper#20]
Thanks for this element!
Saw that you were working on a Polymer 2 element! Is it ready to release? 
I'm referencing #master atm...

**Comment by rubenstolk** [comment]
Hi @JaySunSyn, @dougchestnut sent me the PR and I merged it, I think it's good.

**Comment by JaySunSyn** [comment]
Cool! @dougchestnut is it ready to be released do you think? Or are there issues?

**Comment by JaySunSyn** [comment]
Let's release it @rubenstolk ?

**Comment by dougchestnut** [comment]
I've been using it for a month or two for a carousel banner without problems.  I'm currently on vacation but will pull the latest from master and try it out next week.

**Comment by JaySunSyn** [comment]
Great thanks! I've also made & merged some PRs and released a new version. I've also setup testing boilerplate. Would be great if you still could look into it :) (and maybe even add some tests)

**Comment by rubenstolk** [comment]
Once again, great work @JaySunSyn!

**Comment by rubenstolk** [comment]
I published the demo also: https://safetychanger.github.io/iron-swiper/components/iron-swiper/#/elements/iron-swiper/demos/demo/index.html however it's throwing an error here...
