### ISSUE TITLE
How to use a caption on slider

### ISSUE THREAD

**Issue by shofyanugraha** [safetychanger/iron-swiper#5]
Im new using polymer, and found this slider component. but how can i use a caption in slider. 
Im try like a code below, but doesnt work

``` html
<sc-swiper>
  <div>
     <img src="http://lorempixel.com/640/480/cats">
     <h2 class="text">Lorem ipsum/h2>
     <paper-button class="green">
        register now
     </paper-button>
  </div>
</sc-swiper>
```

**Comment by rubenstolk** [comment]
You could try using:

```
<div>
  <img ... >
  <span class="caption">caption</span>
</div>
```

However, we might have to use more explicit `slot` styling to get this to work with shadow dom.
